### ISSUE TITLE
How to use it with React 15.x

### ISSUE THREAD

**Issue by rathnamvemula** [TrueDub/bootstrap-react-treetable#1]
Hi,
I have an app which is developed using ReactJS 15.x. The component is developed using 16.x. Is there a way, I can use this component in 15.x?

**Comment by TrueDub** [comment]
I don't think so - React 16 has some breaking changes in it, apparently. Sorry about this - there's a number of good reasons to upgrade though, See https://medium.com/@akash.mihul/journey-from-react-15-to-react-16-56e336092379
