### ISSUE TITLE
Using Colspan and Rowspan

### ISSUE THREAD

**Issue by malvinys** [TrueDub/bootstrap-react-treetable#10]
hi, how to use colspan or rowspan like this?

![Screenshot_1](https://user-images.githubusercontent.com/22932211/107728720-632a5880-6d21-11eb-9791-3af4ee702b80.png)

**Comment by TrueDub** [comment]
That's not currently possible.

For headers, only a single header row is used, and for data rows there currently isn't a way of specifying the colspan or rowspan.

I'll investigate this as an enhancement.

**Comment by TrueDub** [comment]
New version 2.0.2 released which allows multi-row headers, with colspan and rowspan enabled.

The existing header row (which provides sorting) is not affected and cannot be altered with colspan or rowspan.

Note that the plugin does not validate your arithmetic on columns or rows, it will render what you specify - testing required!
