### ISSUE TITLE
Change children style

### ISSUE THREAD

**Issue by malvinys** [TrueDub/bootstrap-react-treetable#9]
Hi, how to change the style of children table?

![image](https://user-images.githubusercontent.com/22932211/106871912-572d0e00-6705-11eb-8dca-698f9194263d.png)

**Comment by TrueDub** [comment]
Styling is limited to providing a class to be applied to the TD element(s) of the table.

This is done by using the styleClass attribute of the columns array passed in - a different class can be used for each column.
